# brow_male.py

# Static weighted options for male character describer: eyebrow and forehead variations
WEIGHTED_OPTIONS = [
    ("thick, straight brows with minimal arch and a defined brow bone", 5),
    ("bushy eyebrows with slight natural arch and prominent ridge", 5),
    ("well-groomed medium brows with gentle arch", 4),
    ("straight, low-set brows framing a broad forehead", 4),
    ("arched brows tapering to a fine tail", 3),
    ("heavy brows with a strong furrow and deep forehead crease", 3),
    ("soft, rounded brows above a smooth forehead", 3),
    ("brow ridge with pronounced bone structure and straight brows", 4),
    ("high-set brows with a wide forehead and visible lines", 2),
    ("thick brows meeting in a subtle unibrow", 1),
    ("dark, full brows with a slight downward slope at the ends", 4),
    ("light, sparse brows over a high hairline", 2),
    ("angled brows with sharp peak and smooth forehead", 3),
    ("low, soft brows with horizontal forehead lines", 2),
    ("brow bone shadowed under straight, heavy brows", 3),
    ("arched brows rising over a gentle forehead dome", 3),
    ("thick brows with noticeable forehead wrinkles", 2),
    ("straight brows with feathered edges and smooth brow area", 3),
    ("bushy brows with mid-brow peak and faint frown line", 3),
    ("high-arched brows giving a surprised appearance", 2),
    ("low-arched brows resting close to the eyelid crease", 4),
    ("dense brows casting shadow over the forehead", 2),
    ("arched brows with deep vertical glabellar lines", 1),
    ("long brows extending past the temple with subtle arch", 2),
    ("short, dense brows trimmed neatly above the brow bone", 2),
    ("natural brows with individual hairs visible and a smooth forehead", 3),
    ("straight brows with slight inward tilt and forehead texture", 2),
    ("brow ridge highlighted by low, straight brows and faint lines", 2),
    ("medium arches with clean edges and minimal forehead lines", 4),
    ("heavy, full brows with pronounced furrow lines between brows", 2),
]
