# cheeks_cheekbones_male.py

# Static weighted options for male character describer: combined cheeks and cheekbones variations
WEIGHTED_OPTIONS = [
    ("prominent, high-set cheekbones with flat cheeks", 5),
    ("strong angular cheekbones with slight hollows beneath", 5),
    ("soft cheeks with gentle cheekbone definition", 4),
    ("sunken cheeks highlighting pronounced bones", 4),
    ("fleshy cheeks with rounded contour and mild bones", 3),
    ("chiseled cheeks and sharp bone structure", 5),
    ("broad cheekbones with minimal cheek fullness", 4),
    ("subtle cheekbones blending into smooth cheeks", 3),
    ("well-defined cheek planes with slight hollows", 4),
    ("flat cheek area with understated bone ridge", 2),
    ("strong malar ridge and firm cheek tissue", 4),
    ("rounded cheeks with soft bone curvature", 3),
    ("hollowed cheeks underboard cheekbones", 3),
    ("sculpted cheekbones with taut skin", 4),
    ("cheeks with dimples appearing on smiling", 2),
    ("bony cheeks with thin soft tissue coverage", 2),
    ("broad, full cheeks with gentle bone peaks", 3),
    ("high cheekbones with defined nasolabial lines", 3),
    ("slightly hollowed cheeks and sharp zygomatic bones", 4),
    ("soft, baby-face cheeks with low-set bones", 1),
    ("strong cheek projection with angular contours", 4),
    ("mild cheeks with subtle bone highlights", 3),
    ("deep cheek hollows and pointed bone edges", 2),
    ("rounded cheek fullness with minimal bone prominence", 2),
    ("high and narrow cheekbones with thin cheeks", 3),
    ("square cheek region with flat bone landmarks", 2),
    ("cheeks collapsing slightly inward under bones", 1),
    ("cheeks and bones in harmonious, balanced contour", 4),
    ("soft cheek flesh enveloping moderate bones", 3),
    ("honed, athletic cheeks with taut bone structure", 3),
]
