# chin_male.py

# Static weighted options for male character describer: chin and jawline variations
WEIGHTED_OPTIONS = [
    ("strong square chin with prominent jawline", 5),
    ("slightly pointed chin with defined jaw angle", 4),
    ("broad, cleft chin adding rugged character", 4),
    ("rounded chin flowing into a smooth jaw", 3),
    ("receding chin with subtle jaw taper", 2),
    ("prominent forward chin projection", 3),
    ("soft chin with minimal jaw definition", 2),
    ("wide jawline with firm chin base", 5),
    ("angular jaw tapering to a narrow chin", 4),
    ("square jaw with slight chin cleft", 4),
    ("pointed chin with narrow jaw structure", 3),
    ("strong jaw and flat chin surface", 3),
    ("chin with central dimple and firm jaw", 3),
    ("rounded chin and soft jaw contours", 2),
    ("jawline protruding slightly beyond chin", 2),
    ("balanced chin-to-jaw ratio with subtle cleft", 3),
    ("robust chin with deep mandibular angle", 4),
    ("narrow chin leading into slim jawline", 2),
    ("square chin with heavy jaw prominence", 5),
    ("recessed jaw creating gentle chin slope", 1),
    ("sharp jaw tapering into a small pointed chin", 3),
    ("broad chin blending into strong mandible", 4),
    ("shallow chin with soft jaw edge", 2),
    ("deep chin cleft with sturdy jawline", 3),
    ("chin slightly off-center adding asymmetry", 1),
    ("flat chin with pronounced horizontal mandible", 2),
    ("rounded cleft chin with moderate jaw width", 3),
    ("heavy jawline with minimal chin curvature", 3),
    ("tapered jaw into a narrow, pointed chin", 2),
    ("square chin with softened edges and firm jaw", 4),
]
