# ears_male.py

# Static weighted options for male character describer: ear shape and position variations
WEIGHTED_OPTIONS = [
    ("medium-sized ears with attached lobes close to the head", 5),
    ("small ears with snug, attached lobes and smooth helix", 4),
    ("prominent ears with slightly protruding helix", 4),
    ("large ears with well-defined lobes and shallow ear canal", 3),
    ("rounded ear shape with soft cartilage curves", 3),
    ("oval ears with detached lobes and defined antihelix", 3),
    ("flat ears set close to the skull with minimal projection", 4),
    ("ears with pronounced tragus and distinct helix rim", 2),
    ("ears angled slightly outward from the head", 3),
    ("ears angled inward with narrow concha", 2),
    ("ears with thick cartilage and slightly folded helix", 2),
    ("ears with thin lobes and subtle anti-tragus", 3),
    ("ears with deep concha bowl and strong antihelix", 1),
    ("ears with high-set lobes and wide helix flare", 2),
    ("ears with low-set lobes and narrow helix", 2),
    ("ears featuring a small Darwin’s tubercle on helix", 1),
    ("ears with gently curved helix and smooth antihelix", 4),
    ("ears with prominent earlobe creases and attached lobes", 2),
    ("ears with elongated lobes and faint helix ridge", 3),
    ("ears with pointed upper helix and tight concha", 1),
    ("ears with soft, round lobes and gentle curves", 4),
    ("ears with angular cartilage folds and deep scapha", 2),
    ("ears set higher on head with tapered lobes", 2),
    ("ears set lower with broader lobes and defined helix", 2),
    ("ears with noticeable anti-tragus and subtle rim", 1),
    ("small ears tucked close behind the jawline", 3),
    ("ears with slight protrusion and visible cartilage ridges", 3),
    ("ears with helix folded inward accentuating concha", 1),
    ("ears with thick lobes and shallow antihelix", 2),
    ("ears with gentle outward tilt and smooth lobes", 3),
]
