# expression_female.py

# Static weighted options for female character describer: facial expression variations
# Each description includes the emotion in parentheses
WEIGHTED_OPTIONS = [
    ("neutral expression (neutral)", 5),
    ("slight smile with soft lips (content)", 5),
    ("gentle grin with relaxed eyes (warm)", 4),
    ("broad smile showing subtle joy (happy)", 3),
    ("soft smirk at one corner of the mouth (playful)", 2),
    ("subtle frown with furrowed brow (concerned)", 2),
    ("raised eyebrows and widened eyes (surprised)", 3),
    ("pursed lips and focused gaze (determined)", 2),
    ("slightly parted lips with curious gaze (curious)", 3),
    ("gentle pout with relaxed cheeks (thoughtful)", 2),
    ("narrowed eyes with slight tilt of head (skeptical)", 1),
    ("soft gaze with lowered eyelids (tired)", 2),
    ("wide-eyed stare with open mouth (astonished)", 1),
    ("subtle eyebrow raise and slight head tilt (inquisitive)", 2),
    ("warm half-smile with gentle eyes (kind)", 4),
    ("mischievous grin with playful eyes (mischievous)", 1),
    ("shy smile with slight downward gaze (shy)", 2),
    ("confident smirk with a lifted chin (confident)", 2),
    ("soft laugh lines around eyes (amused)", 2),
    ("serious expression with steady gaze (serious)", 3),
    ("pensive look with lips pressed lightly together (pensive)", 2),
    ("subtle eyebrow furrow and pursed lips (worried)", 1),
    ("gentle tear welling in the eye (sad)", 1),
    ("playful wink with raised eyebrow (flirty)", 1),
    # Additional expressions to broaden emotional range
    ("eyes closed with a serene smile (peaceful)", 2),
    ("brows knitted together with tight lips (frustrated)", 1),
    ("biting lower lip with wide eyes (nervous)", 1),
    ("one eyebrow cocked with sly smile (sly)", 1),
    ("grimace showing clenched teeth (angry)", 1),
    ("distant frown with softened gaze (melancholic)", 1),
    ("subdued smile with downcast eyes (reflective)", 2),
    ("exuberant grin with raised cheeks (excited)", 2),
    ("soft smile with head turned slightly (engaged)", 2),
    ("wide grin with raised chin (proud)", 1),
    ("closed-lip smile with gentle blush (embarrassed)", 2),
    ("furrowed brows with slight lip bite (anxious)", 1),
    ("sneer with parted lips (disdainful)", 1),
    ("tense jaw with narrowed glare (annoyed)", 1),
    ("open mouthed gasp with raised brows (shocked)", 2),
    ("lips pressed together and brow raised (skeptical)", 1),
    ("soft gaze and slight head bow (modest)", 2),
    ("relaxed lips parted in quiet breath (relaxed)", 1),
    ("gentle eyebrow flash and slight nod (approving)", 2),
    ("subtle eye roll with slight smile (sarcastic)", 1),
    ("eyes squeezed shut with playful grin (teasing)", 1),
    ("soft sigh with gentle lip purse (resigned)", 1),
    ("cheekbones lifted in genuine amusement (delighted)", 2),
    ("eyes flickering away with slight blush (embarrassed)", 1),
]