# expression_male.py

# Static weighted options for male character describer: facial expression variations
WEIGHTED_OPTIONS = [
    ("neutral expression with relaxed muscles", 10),
    ("slight smile hinting at warmth", 6),
    ("subtle smirk with one corner raised", 5),
    ("furrowed brow indicating mild concern", 4),
    ("raised eyebrows showing surprise", 4),
    ("tense jaw and narrowed eyes expressing determination", 4),
    ("soft gaze with gentle warmth", 5),
    ("stony expression with impassive eyes", 3),
    ("faint grin with relaxed cheeks", 5),
    ("grimace showing discomfort or pain", 2),
    ("soft frown indicating sadness", 3),
    ("tight-lipped expression suggesting restraint", 3),
    ("bared teeth in a subtle snarl", 2),
    ("wide-eyed shock with open mouth", 1),
    ("raised cheekbones with genuine laughter", 3),
    ("half-closed eyes showing boredom", 2),
    ("anxious glance with pursed lips", 2),
    ("confident grin with lifted chin", 4),
    ("stoic expression with minimal movement", 5),
    ("wry smile with slight head tilt", 4),
    ("thoughtful gaze with distant eyes", 3),
    ("angry glare with flared nostrils", 2),
    ("playful wink and mischievous grin", 2),
    ("pensive look with furrowed brow and soft lips", 3),
    ("determined stare with tightened jaw", 4),
    ("smiling eyes with genuine warmth", 5),
    ("sleepy eyes and relaxed mouth", 2),
    ("mocking smirk with raised eyebrow", 2),
    ("subdued smile with gentle warmth", 4),
    ("intense focus with narrowed eyes and pressed lips", 3),
]
