# eyes_male.py

# Static weighted options for male character describer: eye shape and appearance variations
# Expanded to 60 entries, tailored for male faces across ages and expressions
WEIGHTED_OPTIONS = [
    ("deep-set eyes with a pronounced brow ridge", 5),
    ("almond-shaped eyes with a slight hooded lid", 5),
    ("narrow, intense eyes conveying focus", 4),
    ("round eyes with a warm, approachable gaze", 4),
    ("wide-set eyes giving an open, honest look", 3),
    ("slightly hooded eyes with thick lids", 3),
    ("tired eyes with subtle under-eye shadows", 3),
    ("bright, alert eyes with faint crow's feet", 2),
    ("piercing gaze from sharp, narrow eyes", 3),
    ("soft, kind eyes with gentle creases", 4),
    ("weathered eyes with fine lines and wisdom wrinkles", 1),
    ("youthful eyes with smooth, unlined lids", 4),
    ("piercing blue eyes with intense focus", 2),
    ("warm brown eyes with subtle under-lid bags", 3),
    ("cool gray eyes with a distant stare", 2),
    ("dark brown eyes framed by thick lashes", 3),
    ("light blue eyes with a calm, thoughtful look", 2),
    ("hazel eyes shifting between green and brown", 2),
    ("rich brown eyes with deep, soulful depth", 3),
    ("shallow-set eyes with gentle shadowing", 2),
    ("slightly protruding eyes with subtle epicanthic fold", 1),
    ("hooded eyes with a natural crease above the lid", 3),
    ("soft gaze from mild, rounded eyes", 3),
    ("steely gaze from narrow, piercing eyes", 2),
    ("kind eyes with faint smile lines", 3),
    ("aged eyes with pronounced crow's feet and folds", 1),
    ("sleepy eyes with heavy lids and slight droop", 2),
    ("energetic eyes with wide-open lids and sparkle", 3),
    ("smoldering gaze from half-lidded eyes", 2),
    ("reflective eyes with a distant, thoughtful look", 2),
    ("determined gaze from focused eyes", 4),
    ("compassionate eyes with soft under-eye lines", 3),
    ("mischievous glint in sharp eyes", 2),
    ("confident stare with unwavering intensity", 3),
    ("stern eyes with furrowed brow", 2),
    ("gentle gaze with slight pupil dilation", 3),
    ("fierce eyes with narrowed lids", 2),
    ("dreamy eyes gazing into the distance", 2),
    ("calculating stare with steely focus", 2),
    ("wary eyes scanning the surroundings", 2),
    ("amused eyes with subtle wrinkle at the corners", 3),
    ("pleading eyes with raised inner brows", 2),
    ("frustrated gaze with tense lower lids", 1),
    ("joyful eyes crinkling in genuine laughter", 2),
    ("melancholic eyes with a gentle downward cast", 1),
    ("proud eyes with lifted chin and steady gaze", 2),
    ("shy eyes glancing sideways", 2),
    ("mocking eyes with slight eyebrow raise", 1),
    ("inquisitive eyes with raised outer brows", 2),
    ("resolute gaze with firm eyelid set", 2),
    ("hopeful eyes with slight upward tilt", 3),
    ("weather-beaten eyes with deep furrows", 1),
    ("alert eyes with widened lids", 3),
    ("relaxed eyes with soft lower lids", 3),
]
