# eyes_female.py

# Static weighted options for female character describer: young attractive women in their early 20s
WEIGHTED_OPTIONS = [
    ("bright, large almond-shaped eyes", 5),
    ("large, round doe-like eyes", 5),
    ("sparkling, alert eyes with a defined crease", 4),
    ("softly hooded eyes with long lashes", 3),
    ("slightly upturned eyes with a playful gaze", 3),
    ("deep-set, mysterious eyes", 2),
    ("wide-set eyes with gentle softness", 2),
    ("narrow, cat-eye shaped eyes", 2),
    ("slightly downturned eyes with a wistful look", 1),
    ("almond-shaped eyes with a slight epicanthic fold", 2),
    ("monolid eyes with sleek lids", 1),
    ("large, expressive eyes framed by arched brows", 4),
    ("soft, kind eyes with a gentle arch", 3),
    ("sparkling eyes with subtle lower-lid crease", 3),
    ("deep, soulful eyes with prominent brow ridge", 2),
    ("bright eyes with pronounced under-eye bone", 3),
    ("semi-hooded eyes with a smoldering look", 2),
    ("wide, innocent eyes with long lashes", 3),
    ("narrow, intense eyes set close together", 1),
    ("almond eyes with mid-sized set", 2),
    ("soft round eyes with warm gaze", 3),
    ("soft round eyes with dreamy, introspective look", 2),
    ("lithe, cat-like eyes with tapered outer corners", 2),
    ("gentle doe eyes with a slight upward tilt", 3),
    ("wide, luminous eyes reflecting light like jewels", 3),
    ("almond eyes with elongated outer corners and sparkle", 2),
    ("heart-shaped eyes with a warm, inviting gleam", 2),
    ("hooded eyes with seductive allure at the lash line", 2),
    ("youthful eyes with subtle epicanthal fold and shine", 2),
    ("sparkling gaze hinting at playful curiosity", 3),
    ("bright eyes with prominent double-lid crease", 2),
    ("wide-set eyes with porcelain-white sclera and lash fringe", 2),
    ("soft, kind eyes with a gentle inner corner highlight", 3),
    ("mystic, deep-set eyes accentuated by natural shadows", 1),
    ("wide, open eyes with alert, engaging presence", 3),
    ("slender, almond eyes with delicate lower lid curve", 2),
    ("twinkling, mischievous eyes with a playful sparkle", 3),
    ("piercing, steel-blue eyes with intense focus", 2),
    ("smokey-eyed look with soft eyelid shading", 2),
    ("soft velvety eyelids with a gentle gaze", 3),
    ("mischievous glint in bright eyes", 2),
    ("dreamy, faraway stare", 1),
    ("warm amber eyes glowing softly", 3),
    ("cool gray eyes with a distant charm", 2),
    ("vibrant green eyes flecked with gold", 3),
    ("deep brown eyes rich in warmth", 4),
    ("sparkling hazel eyes shifting color", 3),
    ("icy blue eyes reflecting light", 2),
    ("soft pastel-blue eyes resembling spring sky", 2),
    ("rich chestnut eyes with depth", 3),
    ("twilight mauve eyes with smoky edges", 1),
    ("bright turquoise eyes with tropical hue", 1),
    ("soothing steel-gray eyes with calmness", 2),
    ("shimmering light-brown eyes with golden flecks", 3),
    ("subtle olive-green eyes with unique charm", 2),
    ("warm honey-brown eyes exuding kindness", 3),
    ("bold ebony eyes with dramatic depth", 1),
    ("mesmerizing jade-green eyes", 2),
    ("reflective silver-gray eyes", 1),
    ("bold sapphire-blue eyes", 2),
    ("warm amber-green mixture eyes", 2),
    ("rich cocoa-brown eyes", 3),
    ("soft leaf-green eyes", 2),
    ("bright rose-gold eyes", 1),
    ("deep auburn eyes with fiery undertones", 2),
    ("tranquil aquamarine eyes", 1),
    ("earthy moss-green eyes with subtle depth", 1),
    ("sparkling cognac-colored eyes", 2),
    ("piercing charcoal-gray eyes", 1),
    ("subtly shimmering violet eyes", 1),
]
