# hair_male.py

# Static weighted options for male character describer: hair style (cuts and lengths)
STYLE_OPTIONS = [
    ("buzz cut", 5),
    ("crew cut", 5),
    ("fade haircut", 4),
    ("high and tight", 4),
    ("undercut with fade", 4),
    ("slicked-back undercut", 3),
    ("pompadour", 3),
    ("quiff", 3),
    ("textured crop", 3),
    ("French crop", 3),
    ("side part haircut", 4),
    ("comb over", 3),
    ("slicked back hair", 3),
    ("man bun", 2),
    ("top knot", 2),
    ("long loose hair", 2),
    ("shoulder-length hair", 1),
    ("messy fringe", 3),
    ("curly top with fade", 2),
    ("afro", 1),
    ("dreadlocks", 1),
    ("fade with hairline design", 2),
    ("buzz fade", 4),
    ("Mohawk", 1),
    ("faux hawk", 2),
    ("spiky hair", 3),
    ("bowl cut", 1),
    ("Caesar cut", 2),
    ("mullet", 1),
    ("flowing medium hair", 2),
    ("side-swept fringe", 3),
    ("textured waves", 3),
    ("short textured crop", 3),
    ("long parted hair", 1),
    ("side-shaved undercut", 2),
    ("taper fade", 4),
    ("drop fade", 3),
    ("brush-up haircut", 2),
    ("pompadour with taper", 2),
    ("curly afro fade", 2),
    ("high fade with curls", 2),
    ("low fade haircut", 3),
    ("mid fade haircut", 3),
    ("medium messy cut", 3),
    ("short back and sides", 4),
    ("undercut man bun", 1),
    ("top knot fade", 1),
    ("slick back pompadour", 2),
    ("long slicked-back hair", 1),
    ("shoulder-length waves", 1),
    ("textured fringe fade", 2),
    ("fringed quiff", 2),
    ("classic side part", 3),
    ("modern mullet", 1),
    ("textured comb over", 2),
]

# Static weighted options for hair color (common male shades)
COLOR_OPTIONS = [
    ("black", 5),
    ("dark brown", 5),
    ("medium brown", 4),
    ("light brown", 3),
    ("blond", 4),
    ("dirty blonde", 2),
    ("ash brown", 2),
    ("chestnut", 3),
    ("auburn", 2),
    ("red", 2),
    ("gray", 1),
    ("salt-and-pepper", 1),
    ("platinum blonde", 1),
    ("silver gray", 1),
    ("golden blonde", 2),
]
