# hair_female.py

# Static weighted options for female character describer: hair style (length and cut without color)
# 75 modern college hairstyles and 25 retro era styles, total 100 entries
STYLE_OPTIONS = [
    # Modern college hairstyles (75)
    ("long, straight hair with a center part", 5),
    ("shoulder-length beach waves", 5),
    ("messy high ponytail with face-framing strands", 5),
    ("sleek low ponytail tied with a ribbon", 5),
    ("loose top knot bun with wispy bangs", 5),
    ("half-up half-down hairstyle with a small bun", 4),
    ("double space buns at the crown", 4),
    ("side braid cascading over the shoulder", 4),
    ("messy side braid with flyaway pieces", 4),
    ("tight fishtail braid down the back", 4),
    ("two French braids starting at the crown", 4),
    ("loose Dutch braid framing the face", 4),
    ("pinned-back half-up twists", 4),
    ("soft curls with curtain bangs", 5),
    ("loose spiral curls", 5),
    ("tight ringlet curls", 3),
    ("textured shag with bangs", 4),
    ("layered mid-length bob with waves", 5),
    ("asymmetrical lob with side part", 4),
    ("blunt cut lob with straight ends", 4),
    ("wavy lob with subtle roots", 4),
    ("curly bob with defined coils", 3),
    ("pixie cut with long fringe", 3),
    ("undercut bob with shaved sides", 2),
    ("sleek one-length lob", 3),
    ("messy beach waves", 5),
    ("braided half-crown updo", 3),
    ("low messy bun with loose tendrils", 5),
    ("classic sleek bun at nape", 4),
    ("side-swept straight hair", 5),
    ("straight hair with micro bangs", 3),
    ("textured curled ends", 4),
    ("soft layered curls", 4),
    ("long straight hair with curtain bangs", 5),
    ("swept-over side bangs and waves", 4),
    ("baby bangs with bob", 2),
    ("hair with soft feathered layers", 5),
    ("curtain bangs with loose waves", 4),
    ("half-up braided crown", 4),
    ("space ponytails", 3),
    ("bubble ponytail", 3),
    ("high sleek bun", 4),
    ("low twisted ponytail", 4),
    ("scarf wrapped around ponytail", 3),
    ("hair wrapped around a top knot", 3),
    ("French twist updo", 2),
    ("braided chignon", 2),
    ("classic straight hair with side part", 5),
    ("beach wave bob", 4),
    ("wavy layered mid-length hair", 4),
    ("sleek long hair with no bangs", 5),
    ("loose soft curls shoulder-length", 4),
    ("loose natural waves", 5),
    ("pin-straight hair with inward curl at ends", 4),
    ("hair with subtle ombre transitions", 3),
    ("mid-length waves with curtain bangs", 4),
    ("ducktail braid hairstyle", 2),
    ("twisted pigtail braids", 2),
    ("hair with a bold middle part", 4),
    ("hair parted slightly off-center", 5),
    ("medium-length hair with tousled texture", 4),
    ("curly hair with volume", 4),
    ("straight hair with slight wave at ends", 4),
    ("textured lob with curtain bangs", 3),
    ("high-low ponytail", 3),
    ("braided pigtails", 3),
    ("low pigtails", 3),
    ("sleek ponytail wrapped at base", 4),
    ("loose plait hair", 3),
    ("soft curls with deep side part", 4),
    ("straight hair with side-swept bangs", 5),
    ("medium waves", 4),
    ("curly hair with side braids", 3),
    ("messy bun with loose strands", 4),
    ("wrapped low ponytail", 3),
    # Retro era styles (25)
    ("1920s finger waves in bob", 2),
    ("1930s Marcel wave shoulder-length hair", 2),
    ("1940s victory rolls with prominent curls", 2),
    ("1950s curled ends with voluminous rolls", 2),
    ("1960s beehive hairstyle", 2),
    ("1960s flipped ends hairdo", 2),
    ("1970s feathered layers à la Farrah Fawcett", 2),
    ("1970s shag haircut", 2),
    ("1980s big teased hair with volume", 1),
    ("1980s crimped hair style", 1),
    ("1990s sleek straight center-parted hair", 1),
    ("1990s grunge messy hair", 1),
    ("1950s pin-up curls with bangs", 2),
    ("1960s bouffant", 1),
    ("1920s cloche-style close crop", 1),
    ("1930s sleek rolled bob", 1),
    ("1940s pin curls framing the face", 2),
    ("1950s ponytail with a ribbon", 2),
    ("1960s short pixie cut", 2),
    ("1970s afro style", 1),
    ("1980s mullet", 1),
    ("1990s butterfly clips in hair", 1),
    ("1980s side ponytail with scrunchie", 1),
    ("1990s half-up scrunchie style", 1),
    ("1970s long straight hair with center part", 2),
]

# Expanded hair color options
COLOR_OPTIONS = [
    ("dark brown", 5),
    ("light blonde", 5),
    ("black", 6),
    ("auburn", 3),
    ("brunette", 4),
    ("blonde", 4),
    ("red", 1),
    ("chestnut", 3),
    ("platinum blonde", 1),
    ("honey blonde", 2),
    ("strawberry blonde", 2),
    ("ash brown", 3),
    ("sandy blonde", 2),
    ("chocolate brown", 3),
    ("copper red", 1),
    ("caramel brown", 2),
    ("deep black", 3),
    ("rosy brown", 1),
    ("golden brown", 2),
]