# makeup_female.py

# Static weighted options for female character describer: makeup style variations
# Low-makeup looks are more common (higher weights); bold, high-makeup looks are rare (weight 1)
WEIGHTED_OPTIONS = [
    ("natural, no-makeup look", 6),
    ("barely-there tinted moisturizer", 5),
    ("sheer foundation with minimal coverage", 5),
    ("light brow filling for a polished look", 5),
    ("light mascara emphasizing upper lashes", 5),
    ("subtle eyeshadow wash for natural depth", 5),
    ("soft blush accent on cheeks", 5),
    ("subtle highlighter on cheekbones", 5),
    ("matte finish with softly defined contours", 4),
    ("dewy finish with gentle luminosity", 4),
    ("soft highlight on cupid's bow", 4),
    ("thin, defined eyeliner along upper lash line", 4),
    ("barely-there eyeliner flick at lash tips", 3),
    ("barely-there shimmer on eyelids", 3),
    ("light bronzer accentuating cheekbones", 3),
    ("subtle contour under cheekbones", 3),
    ("matte base with even skin tone", 4),
    ("fine dusting of translucent powder", 4),
    ("soft gradient eyeshadow in neutral tones", 3),
    ("minimal crease definition on eyelids", 3),
    ("light lower-lash mascara", 2),
    ("subtle tightlining of the upper waterline", 2),
    ("slight winged eyeliner flick", 2),
    ("light highlight on brow bone", 3),
    ("tinted lip balm effect", 3),
    ("barely-there lip liner to define shape", 2),
    ("soft contour on the nose bridge", 2),
    ("gentle brow gel to shape eyebrows", 3),
    ("matte finish under eyes to reduce shine", 4),
    ("soft eyebrow arch accentuation", 3),
    ("soft highlight on inner eye corners", 2),
    ("delicate lash tint enhancing natural lashes", 2),
    ("refined light base for a polished complexion", 3),
    ("soft airbrushed effect on skin texture", 3),
    ("minimal contour on jawline", 2),
    ("subtle emphasis on cheek hollows", 2),
    ("soft veil of luminous primer", 2),
    ("lightly blurred skin finish", 2),
    ("slight brow bone emphasis", 2),
    ("vibrant bold lips for a statement look", 1),
    # Lipstick color options
    ("classic red lipstick", 1),
    ("cherry red lipstick", 1),
    ("soft rose lipstick", 2),
    ("nude peach lipstick", 2),
    ("berry pink lipstick", 2),
    ("deep plum lipstick", 1),
]
