# mouth_male.py

# Static weighted options for male character describer: mouth and lip shape variations (size, shape, corner set)
WEIGHTED_OPTIONS = [
    ("broad mouth with straight, firm lips", 5),
    ("medium-width mouth with balanced proportions", 5),
    ("narrow mouth with thin lips", 4),
    ("full lower lip with slightly thinner upper lip", 4),
    ("straight-lined lips forming a neutral expression", 5),
    ("wide mouth with gently upturned corners", 4),
    ("softly curved lips with natural fullness", 3),
    ("tight lips pressed together in a firm line", 4),
    ("slight part between lips revealing a hint of teeth", 3),
    ("downturned corners lending a serious look", 3),
    ("regular-sized mouth with even lip thickness", 5),
    ("broad smile line even at rest", 4),
    ("tightly drawn lips suggesting restraint", 2),
    ("lips with slight crease at the center", 3),
    ("straight mouth line extending evenly at corners", 4),
    ("soft lip contour with minimal definition", 3),
    ("broad mouth with slight asymmetry between corners", 3),
    ("subtle notch in upper lip center", 2),
    ("thin lips with pronounced philtrum", 2),
    ("thick lips with balanced proportions", 2),
    ("flat lips with minimal curvature", 3),
    ("uneven mouth corners giving a lopsided look", 1),
    ("downturned mouth with firm closure", 2),
    ("slightly upturned lips conveying subtle warmth", 2),
    ("firm lips with a straight horizontal line", 4),
    ("slight smile line but lips at rest", 3),
    ("firm pressed lips with slight puckering", 2),
    ("evenly thin lips with crisp edges", 2),
    ("narrow lips with sharp cupid's bow", 2),
    ("wide mouth with defined upper lip ridge", 3),
    ("lips with faint vertical creases", 2),
    ("medium lips with a square edge", 2),
    ("rounded lips with angular outer corners", 2),
    ("lips parted in a subtle half-smile", 1),
    ("firm lips with a tense center dip", 2),
    ("broad lips with gentle central curve", 3),
    ("flat lip posture with minimal set", 2),
]
