# nose_male.py

# Static weighted options for male character describer: nose shape and profile variations
# Expanded to 60 entries, including a broken nose option
WEIGHTED_OPTIONS = [
    ("strong straight bridge with defined tip", 5),
    ("slightly aquiline profile with subtle curve", 5),
    ("broad nose with gently flared nostrils", 4),
    ("narrow nose tapering to a refined tip", 4),
    ("classic Roman nose with prominent bridge", 3),
    ("slightly hooked nose with confident profile", 3),
    ("straight slender nose with smooth contours", 5),
    ("rounded bulbous tip adding character", 2),
    ("snub nose with gentle upturn at the tip", 3),
    ("strong ridge with subtle nostril flare", 4),
    ("long nose with narrow bridge and defined tip", 3),
    ("short nose with a firm, structured tip", 3),
    ("softly curved nose with minimal projection", 2),
    ("broad, flat bridge with a sturdy shape", 2),
    ("prominent dorsal hump softened by tip rounding", 2),
    ("nose with a straight profile and slight taper", 4),
    ("gentle concave bridge leading to a rounded tip", 2),
    ("strong, angular nose with a prominent bridge", 3),
    ("narrow nose with delicate nostril shape", 3),
    ("slightly upturned tip with masculine structure", 3),
    ("wide base nose with defined alar rims", 2),
    ("long straight nose with balanced proportions", 4),
    ("Roman bump on bridge with refined tip", 1),
    ("snub nose with light masculine flair", 2),
    ("straight high bridge with soft-rounded tip", 3),
    ("nose with a subtle saddle effect", 1),
    ("broad nose softened by gentle rounding", 2),
    ("bridge with slight ridge and clean lines", 3),
    ("narrow flared nostrils and straight profile", 2),
    ("strong tip projection with defined shape", 3),
    ("nose with visible healed fracture and slight bump", 1),
    # Additional variations
    ("flattened tip with gentle asymmetry", 2),
    ("crooked bridge adding rugged character", 2),
    ("high nasal bridge and narrow tip", 4),
    ("low bridge with small rounded tip", 3),
    ("prominent tip with pronounced columella", 2),
    ("slender bridge with wide nostrils", 2),
    ("subtle dorsal ridge accentuating profile", 3),
    ("soft nasal hump blending smoothly", 2),
    ("aquiline nose with dramatic curve", 1),
    ("broad scoop nose with defined alae", 1),
    ("squared-off tip giving strong presence", 2),
    ("sharp, narrow bridge with thin tip", 3),
    ("rounded alae with slight flaring", 3),
    ("raised columella showing defined nasal base", 2),
    ("long slender nose reminiscent of classical statues", 1),
    ("slight crook at the bridge for distinctive profile", 2),
    ("nose with keratinized skin texture on the bridge", 1),
    ("dished bridge with shallow concavity", 1),
    ("strong, Romanesque bridge with sharp tip", 2),
    ("wide nostrils tapering to a narrow bridge", 2),
    ("straight bridge with subtle alar flare", 3),
    ("small, compact nose with defined tip", 3),
    ("nose with slight dorsal deviation to one side", 1),
]
