# nose_female.py

# Static weighted options for female character describer: young attractive women in their early 20s
WEIGHTED_OPTIONS = [
    ("delicate, slightly upturned button nose", 5),
    ("straight, slender bridge with softly rounded tip", 5),
    ("small, refined snub nose", 4),
    ("narrow, elegant nose with subtle definition", 4),
    ("slightly aquiline nose with gentle curve", 3),
    ("softly rounded nose with a smooth contour", 3),
    ("petite nose with a subtle arch", 3),
    ("straight nose with defined nasal bridge", 2),
    ("slender nose tapering to a refined tip", 2),
    ("broad, balanced nose with gentle slope", 2),
    ("snub nose with a cute, buttoned appearance", 3),
    ("aquiline nose giving a classic profile", 2),
    ("slight dorsal hump softened by smooth skin", 1),
    ("small nose with faint upturn and charm", 3),
    ("sculpted nose with high, narrow bridge", 2),
    ("softly flared nostrils adding gentle character", 2),
    ("straight nose complemented by smooth alae", 2),
    ("nose with slender bridge and subtle flare", 3),
    ("rounded, baby-doll nose with youthful appeal", 4),
    ("lean nose with defined nasal ridge and tip", 2),
    ("soft, subtly curved nose with feminine contour", 3),
    ("petite nose with delicate nostril shape", 3),
    ("elegant ski-jump nose with gentle tip tilt", 1),
    ("slender nose with faint ridge and refined tip", 2),
    ("nose with smooth bridge and rounded tip", 3),
    ("small nose with whispered upturn at the end", 1),
    ("straight profile nose with classic symmetry", 3),
    ("nose with soft dip and rosebud tip", 2),
    ("button nose with a hint of charm and youthfulness", 4),
    ("slightly concave bridge adding subtle depth", 1),
]
