# skin_female.py

# Static weighted options for female character describer: skin appearance variations (tone, texture, subtle marks)
WEIGHTED_OPTIONS = [
    ("smooth, porcelain complexion with minimal visible pores", 5),
    ("soft matte skin with even texture", 5),
    ("dewy, luminous skin finish with fine pores", 4),
    ("silky skin surface with a subtle natural glow", 4),
    ("flawlessly even skin tone with no marks", 5),
    ("light scattering of freckles across nose and cheeks", 3),
    ("few delicate freckles framing the cheekbones", 3),
    ("subtle beauty mark near the temple", 2),
    ("small mole just above the jawline", 2),
    ("slightly flushed skin with a healthy tint", 3),
    ("slight natural pores visible under close inspection", 3),
    ("fine texture with a few faint freckles", 2),
    ("smooth skin with one distinct beauty mark by the lip", 2),
    ("clear skin with a dusting of light freckles", 3),
    ("even skin with a single, small mole on the cheek", 2),
    ("softly radiant skin with minimal sheen", 4),
    ("matte complexion with a velvety finish", 4),
    ("skin showing subtle texture and natural pores", 3),
    ("porcelain skin with one tiny beauty spot", 2),
    ("gently warm skin undertone with smooth texture", 3),
    # Additional options to expand diversity:
    ("translucent skin showing faint veins at the temples", 2),
    ("smooth skin with a subtle highlight on cheekbones", 3),
    ("barely visible pores with a soft silk-like finish", 3),
    ("balanced skin tone with a slight inner luminosity", 2),
    ("skin with fine, imperceptible freckles across cheeks", 2),
    ("skin texture blending matte areas with a gentle glow", 3),
    ("clear skin with no blemishes or visible marks", 5),
    ("even pores with slight warmth around the cheek area", 2),
    ("skin with minimal high points and smooth flat planes", 2),
    ("subtle freckle cluster near the bridge of the nose", 2),
    ("smooth jawline skin free of visible pores", 3),
    ("soft forehead skin with no lines or marks", 3),
    ("under-eye area showing clear, even skin texture", 3),
    ("skin on temples with gentle shadowing and smoothness", 2),
    ("cheek area with a subtle highlight but no shine", 2),
    ("skin with gentle microtexture and minimal variation", 3),
    ("skin appearing refreshed with natural clarity", 3),
    ("uniform skin texture with no visible imperfections", 4),
]
