# skin_male.py

# Static weighted options for male character describer: skin traits and surface variations
WEIGHTED_OPTIONS = [
    ("clear, smooth skin with even tone", 5),
    ("light stubble shadow on the jaw and cheeks", 5),
    ("slight five o'clock shadow around chin and upper lip", 4),
    ("visible pores and natural skin texture", 4),
    ("subtle freckles across the nose bridge and cheeks", 3),
    ("light acne scars on cheeks from past breakouts", 2),
    ("sun-kissed tan with warm undertones", 4),
    ("pale complexion with cool undertones", 3),
    ("rough, weathered skin with fine lines", 2),
    ("smooth skin with faint forehead wrinkles", 3),
    ("slight redness around nose and cheeks", 2),
    ("matte, dry skin with minimal shine", 3),
    ("light rosacea on cheek areas", 1),
    ("visible sun spots on cheeks and forehead", 1),
    ("acne blemishes on the lower face", 2),
    ("uneven skin tone with faint discoloration", 2),
    ("smooth complexion with subtle glow", 4),
    ("slight stubble-induced shadow and texture", 4),
    ("prominent jaw shadow from dense stubble", 3),
    ("freckles across nose and forehead", 2),
    ("mole on left cheek", 1),
    ("scar on eyebrow ridge", 1),
    ("wrinkle lines at the corners of the eyes", 2),
    ("faint nasolabial folds", 3),
    ("light sunburn redness on nose and cheeks", 1),
    ("oil sheen on forehead and chin", 2),
    ("slightly rough skin with small bumps", 2),
    ("smooth, well-hydrated skin texture", 4),
    ("aging skin with deeper forehead lines", 1),
]
